### ISSUE TITLE
Dragging to zoom doesn't work for data with timestamps below a certain size

### ISSUE THREAD

**Issue by jamespwilliams** [vasturiano/timelines-chart#115]
I've created a couple of jsfiddles to illustrate the problem. The fiddles are identical, other than that in one of them the timestamps are 1000x smaller than the other:

* https://jsfiddle.net/x9p4an3g/14/ (smaller timestamps)
* https://jsfiddle.net/nwe5o9ub/1/ (larger timestamps)

Dragging to zoom the chart only changes the X axis for the larger timestamp example. With the smaller timestamp data, no change is  made to the X axis on drag.

https://jsfiddle.net/nwe5o9ub/3/ is an example with data somewhere between the two. In this one, large selections do work, but smaller ones don't.

In all cases using the overview bar works fine.

**Comment by vasturiano** [comment]
@jamespwilliams thanks for reaching out.

The progressive zoom (drag on main chart) had a smallest window size of 1min. I've reduced this to one second. The reason why there needs to be an eventual limit is because otherwise you could keep zooming in to microscopical time ranges which has the potential of getting the user lost.

With the overview bar this is less of an issue since you only have so many pixels of definition, which naturally won't permit very small time ranges.
