### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by Royalxm** [vasturiano/timelines-chart#20]
Hello,

can I change the colors? for example letter if (val == A) color = red

for example or in json put data + val + color

**Comment by vasturiano** [comment]
@Royalxm you can use the method `.zColorScale(<d3 scale>)` to configure the colors of the chart.

If you're using it in qualitative mode, make sure to use an instance of [scaleOrdinal](https://github.com/d3/d3-scale#scaleOrdinal), otherwise use a [scaleSequential](https://github.com/d3/d3-scale#scaleSequential) instead.

**Comment by Royalxm** [comment]
Thx you 

example :
```
    
var color = d3.scaleOrdinal() // D3 Version 4
                    .domain(["A", "B", "C"])
                    .range(["#009933", "#FF0000" , "#0000ff"]);
                TimelinesChart()(document.body)
                    .zColorScale(color)
                    .zQualitative(false)
                    .data(data);
```
