### ISSUE TITLE
Resize chart

### ISSUE THREAD

**Issue by foreveRush** [vasturiano/timelines-chart#5]
Hi! First of all, thank you for good lib!

I have next code:
```
this.chart = TimelinesChart();
chart
    .data(oldData)
    .width(oldWidth)
    (document.getElementById("classificationChart" + widgetConf.id));
```

Later I want to resize chart and use `refresh` function:
```
this.chart
       .data(newData) // or oldData
       .width(newWidth)
       .refresh();
```

Data is changing but the width is the same. Is it some bug?

**Comment by vasturiano** [comment]
Thanks @foreveRush for the report. This was a bug disguised as a feature. :) Width (and margins) were an initialization prop only and the chart wasn't responding to changes on these values.
This has been fixed in `v2.3.0`, if you use the latest version you should see the chart's dimensions updating when using the above code.
It's also no necessary to call `.refresh()`, the chart will automatically update when any of the setter methods are called.
