### ISSUE TITLE
Include HTML in labels/groups

### ISSUE THREAD

**Issue by alexoakland** [vasturiano/timelines-chart#8]
I have implemented timelines-chart into a project I am working on, and have come across a need to include HTML in labels and groups, specifically for links. I've looked through the docs provided and the code itself and haven't found that as an option or a way to implement it.

Would it be possible to have this added as a feature/have some insight on how to implement it.

Thanks.

**Comment by vasturiano** [comment]
@alexoakland currently it's not possible to set custom html as the axis labels, mainly because those elements are actually SVG text elements and not plain div/span HTML elements.

However, if your intent is to turn those labels into clickable links, you can do so using the `onLabelClick` callback, to which you can attach whichever behavior you need, including link redirection.

If you wish to style the labels differently you can also do that by extending the CSS targeting those specific elements.

Let me know if this solves your use case.

**Comment by alexoakland** [comment]
Sorry for the delay in replying. That solved the issue, thanks. 

However, in the process of implementing the change, I have come across another issue. I have got two timelines-chart's on one page, and when zooming in on one of the charts, it causes the hover effect to break on the other chart, in that the plots on the chart end up rising to the very top of the chart, resulting in a need to refresh the page to put the chart back to normal. 

I have attached a screenshot below showing the issue. The top chart is zoomed in, and the highlighted section of the bottom chart is where the plots have risen from the bottom of the chart to the top. 
<img width="1620" alt="screen shot 2017-12-19 at 13 23 00" src="https://user-images.githubusercontent.com/19596418/34159200-4d2bf8fa-e4c0-11e7-911e-345c879ca501.png">

Thanks.

**Comment by vasturiano** [comment]
Thanks for reporting that @alexoakland! That was definitely a bug in the library, due to some undesired sharing of state between component instance. That's now fixed in v2.4.1, so if you upgrade to that version you shouldn't have the issue anymore.
